# Twitter API Credentials
twitter.consumer.key=enWcf6y7UlguHhWGrJ3ESZfwv
twitter.consumer.secret=Qkm3dVJCiKtZdzGBp4S9Ii52oHcJ85MUJMFal71lYPvwoWP9kQ
twitter.access.token=954842321127919617-vybpBPRzncLAhahtmfZyXUvCQ0Ckq1v
twitter.access.token.secret=2eqFbFIv53YrEHA4Sc4YvJ4qfo3LjkSPAqXsWecsDncPo

# Kafka Configuration
kafka.bootstrap.servers=localhost:6667
kafka.topic=tweets_topic
kafka.zookeeper.connect=sandbox-hdp.hortonworks.com:2181

# HDFS Configuration
hdfs.path=hdfs://localhost:9000/twitter-data 